 # pandas

In [1]:
import pandas as pd

In [2]:
#Series
a = pd.Series([1,5,2,3,5])
print(a)

0    1
1    5
2    2
3    3
4    5
dtype: int64

In [3]:
a=pd.Series(([1,5,2,3,5]),index=(['a','b','c','d','e']))
a

a    1
b    5
c    2
d    3
e    5
dtype: int64

In [4]:
n={'name':["amit","pra","rohit"],
   'age':[20,25,30],
   'city':["pune","nashik","mumbai"]
  }

In [5]:
df = pd.DataFrame(n)

In [6]:
print(df)

    name  age    city
0   amit   20    pune
1    pra   25  nashik
2  rohit   30  mumbai

In [7]:
m={'employee':["rd","kl","srk"],
   'salary':[34000,40000,15000],
   'address':['pune','nashik','thane']
  }

In [8]:
df =pd.DataFrame(m)

In [9]:
df

  employee  salary address
0       rd   34000    pune
1       kl   40000  nashik
2      srk   15000   thane

## row called index value,observation,values,record
## cpolumn called varibles,dimention,fiels,fetures

In [10]:
import numpy as np

In [11]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
df = pd.DataFrame(a)

In [14]:
pd.DataFrame(a,columns=["a","b","c"])

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

pd.DataFrame(l)

In [15]:
df =pd.DataFrame(m)

In [16]:
df

  employee  salary address
0       rd   34000    pune
1       kl   40000  nashik
2      srk   15000   thane

In [17]:
df.info(m)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   employee  3 non-null      object
 1   salary    3 non-null      int64
 2   address   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [18]:
df.describe()

             salary
count      3.000000
mean   29666.666667
std    13051.181300
min    15000.000000
25%    24500.000000
50%    34000.000000
75%    37000.000000
max    40000.000000

In [19]:
df.shape

(3, 3)

In [20]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [21]:
df.columns

Index(['employee', 'salary', 'address'], dtype='object')

In [22]:
df.head(2)

  employee  salary address
0       rd   34000    pune
1       kl   40000  nashik

In [23]:
df.tail(1)

  employee  salary address
2      srk   15000   thane

In [24]:
df["id"]=[23,55,70]

In [25]:
df

  employee  salary address  id
0       rd   34000    pune  23
1       kl   40000  nashik  55
2      srk   15000   thane  70

In [26]:
df['salary']=df['salary'].apply(lambda r:r*200)

In [27]:
df

  employee   salary address  id
0       rd  6800000    pune  23
1       kl  8000000  nashik  55
2      srk  3000000   thane  70

In [ ]:
df.to_csv(".csv"index=False)